IF OBJECT_ID('dbo.reclamos_procesados', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.reclamos_procesados (
        claim_number NVARCHAR(100) NOT NULL,
        plataforma NVARCHAR(50) NOT NULL,
        createdon DATETIMEOFFSET NULL,
        status NVARCHAR(100) NULL,
        tipo_garantia NVARCHAR(100) NULL,
        fc_expiration DECIMAL(10,4) NULL,
        repair_deadline DECIMAL(10,4) NULL,
        claim_deadline DECIMAL(10,4) NULL,
        technical_report DECIMAL(10,4) NULL,
        invoices DECIMAL(10,4) NULL,
        work_order DECIMAL(10,4) NULL,
        photographs DECIMAL(10,4) NULL,
        fc_expiration_reason NVARCHAR(MAX) NULL,
        repair_deadline_reason NVARCHAR(MAX) NULL,
        claim_deadline_reason NVARCHAR(MAX) NULL,
        technical_report_reason NVARCHAR(MAX) NULL,
        invoices_reason NVARCHAR(MAX) NULL,
        work_order_reason NVARCHAR(MAX) NULL,
        photographs_reason NVARCHAR(MAX) NULL,
        cost_coverage_labor DECIMAL(10,4) NULL,
        cost_coverage_labor_reason NVARCHAR(MAX) NULL,
        cost_coverage_other_expenses DECIMAL(10,4) NULL,
        cost_coverage_other_expenses_reason NVARCHAR(MAX) NULL,
        cost_coverage_mileage DECIMAL(10,4) NULL,
        cost_coverage_mileage_reason NVARCHAR(MAX) NULL,
        comentario NVARCHAR(MAX) NULL,
        powerapps_id NVARCHAR(150) NULL,
        within_standard_warranty DECIMAL(10,4) NULL,
        within_standard_warranty_reason NVARCHAR(MAX) NULL,
        standard_rate DECIMAL(10,4) NULL,
        standard_rate_reason NVARCHAR(MAX) NULL,
        root_cause_analysis DECIMAL(10,4) NULL,
        root_cause_analysis_reason NVARCHAR(MAX) NULL,
        cost_coverage_parts DECIMAL(10,4) NULL,
        cost_coverage_parts_reason NVARCHAR(MAX) NULL,
        -- ── Nuevas columnas para EDT Factory Warranty (Adjuntos) ──
        attachments_plm DECIMAL(10,4) NULL,
        attachments_plm_reason NVARCHAR(MAX) NULL,
        attachments_oil_analysis DECIMAL(10,4) NULL,
        attachments_oil_analysis_reason NVARCHAR(MAX) NULL,
        attachments_datapacks DECIMAL(10,4) NULL,
        attachments_datapacks_reason NVARCHAR(MAX) NULL,
        attachments_technical_report_sf DECIMAL(10,4) NULL,
        attachments_technical_report_sf_reason NVARCHAR(MAX) NULL,
        attachments_photographs_sf DECIMAL(10,4) NULL,
        attachments_photographs_sf_reason NVARCHAR(MAX) NULL,
        total_adjuntos INT NULL,
        adjuntos_en_claim INT NULL,
        adjuntos_en_case INT NULL,
        modelo NVARCHAR(100) NULL,
        serial_number NVARCHAR(100) NULL,
        submitted_date DATETIMEOFFSET NULL,
        coverage_type NVARCHAR(100) NULL,
        claim_type__c NVARCHAR(100) NULL,
        repair_date DATETIMEOFFSET NULL,
        part_installation_date DATETIMEOFFSET NULL,
        part_installation_date_reason NVARCHAR(MAX) NULL,
        purchase_invoice DECIMAL(10,4) NULL,
        purchase_invoice_reason NVARCHAR(MAX) NULL,
        -- ── SPCR informativo 0-1 para PA - Special Policy (no resta peso) ──
        attachments_special_policy DECIMAL(10,4) NULL,
        attachments_special_policy_reason NVARCHAR(MAX) NULL,
        ia_calls INT NULL,
        ia_input_tokens BIGINT NULL,
        ia_output_tokens BIGINT NULL,
        ia_estimated_cost_usd DECIMAL(10,4) NULL,
        raw_payload_json NVARCHAR(MAX) NULL,
        created_at DATETIME2 NOT NULL CONSTRAINT DF_reclamos_created_at DEFAULT SYSUTCDATETIME(),
        updated_at DATETIME2 NOT NULL CONSTRAINT DF_reclamos_updated_at DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_reclamos_procesados PRIMARY KEY (claim_number, plataforma)
    );

    CREATE INDEX IX_reclamos_procesados_createdon ON dbo.reclamos_procesados (createdon);
END
